// Mocks generated by Mockito 5.0.5 from annotations
// in numbers/test/numbers_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:numbers/numbers/api/api_client.dart' as _i2;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i2.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> eImpfpass() =>
      (super.noSuchMethod(Invocation.method(#eImpfpass, []),
          returnValue: Future<String>.value('')) as _i3.Future<String>);
}
