name: numbers
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  flutter_riverpod: ^0.14.0+2
  retrofit: ^2.0.0-beta1
  csv: ^5.0.0
  intl: ^0.17.0

dev_dependencies:
  build_runner: ^1.12.2
  flutter_test:
    sdk: flutter
  mockito: ^5.0.5
  retrofit_generator: ^2.0.0-beta3

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
